### Primer arreglo Numpy

La lista baseball contiene las alturas de algunos jugadoresen cm.

¿Podrias agregar el código para convertirlo en un arreglo numpy?

In [2]:
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

np_baseball= np.array(baseball)

print(type(np_baseball))
print(np_baseball)

<class 'numpy.ndarray'>
[180 215 210 210 188 176 209 200]


### Alto de los jugadores

Como gran fan de baseball, decides llamar a la MLB y pedirles un poco más información sobre la estatura de los jugadores principales.
Ellos te envían datos de más de mil jugadores, los cuales están almacenados en una lista convencional de Python

`height_in`. La altura está expresada en pulgadas. Podrías crear un arreglo `numpy` y convertir las unidades a metros?

Para eso se multiplicará el dato por 0.0254

Además se tendrán que crear 1015 datos aleatorios en la variable `height_in`

In [3]:
import random

height_in=[]
weight_lb=[]

for i in range(0, 1014):
    height_in.append(random.randint(67,83))
    weight_lb.append(random.randint(150,290))
    
#Pasamos el arreglo a tipo Numpy

np_height_in=np.array(height_in)
np_weight_lb=np.array(weight_lb)

#lo imprimimos
print(np_height_in)

# Lo convertimos en metros e imprimimos
np_height_m=np_height_in*0.0254

print(np_height_m)

[67 73 83 ... 78 76 80]
[1.7018 1.8542 2.1082 ... 1.9812 1.9304 2.032 ]


### Calcular el Indice de Masa Corporal de los jugadores

Para lograr esto necesitamos calcular

$$BMI= \frac{weight\, (kg)}{height\,(mts)^2}$$

[Markdown para fórmulas matemáticas](https://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/)

Crear un arreglo en numpy para la lista de pesos en libras, multiplicarlos por 0.453592 para pasar los datos de libras a kg. Almacena el resultado como `np_weight_kg` 

Usa la atura y el peso para calcular el BMI, almacena el resultado en el arreglo `bmi` e imprimelo.

In [4]:
# El vector de pesos ya fue creado np_weight_lb

np_weight_kg=np_weight_lb*0.453592

bmi=np_weight_kg/np_height_m**2


print(bmi)

[36.49255479 35.35794589 24.18745166 ... 26.34775368 25.31827446
 18.45556141]


### Buscar con condiciones

Para buscar en las listas normales, se puede utilizar el índice en los corchetes. En numpy específicamente se pueden utilizar valores en arreglos booleanos.

El código que calcula el BMI ya está incluido

- Crea un arreglo boleano numpy, el elemento del arreglo debe ser True si el índice de masa es menor a 21. Nombra al arreglo `light`.

- Imprime el arreglo.
- Imprime los BMI de los jugadores utilizando el arreglo `light`.




In [5]:
light=bmi<21

print(light)

print(bmi[light])


[False False False ... False False  True]
[19.77221091 19.7738158  18.37409138 19.4984471  17.33404847 17.35714679
 19.99840729 20.81454294 20.46733427 19.13468592 19.92167196 18.02452187
 17.90578848 20.56973752 20.39599748 18.14295125 20.63316024 20.67094777
 20.12339733 16.83936508 20.870323   19.71904068 18.99848692 20.02899287
 19.33439767 18.74850683 20.39599748 20.59854167 17.04347859 19.25864699
 20.79933875 20.98221565 18.08907467 18.53847555 20.20593058 19.77221091
 18.13717513 18.47513492 16.89798925 19.33439767 18.75279318 17.79628977
 18.47227321 16.63525156 20.38941942 20.68165191 19.8666138  20.41135161
 20.9216354  19.90060189 20.88592341 18.45556141 18.83633268 18.8130947
 19.28872727 20.58149089 19.76205267 19.08461375 16.60961682 16.47817983
 17.23594904 20.81957864 17.14553535 17.03825209 17.24759211 16.63525156
 17.68657969 20.59854167 17.7872071  19.60166753 19.03840122 19.65749155
 20.98221565 20.04025334 19.34380817 20.76250659 19.00483407 20.15738385
 19.084613

## Type en Arreglos Numpy

Si se tiene un arreglo bidimensional o ndimensional en numpy, podemos saber la cardinalidad del arreglo con el método `shape`

`bmi.shape`

Podemos acceder a los miembros del arreglo con los corchetes de forma tradicional `bmi[1][0]` o por medio de una comma `bmi[1,0]` 

Supongamos que necesitamos los datos del segundo y tercer miembro de dos arreglos dentro del arreglo, entonces colocamos dos puntos antes de la comma. `bmi[:,1:3]` esto nos da un arreglo de 2x2 

También se podría seleccionar todo el segundo arreglo de esta forma `bmi[1,:]`

### Arreglo bidimensional 2D con Numpy


In [6]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

np_baseball=np.array(baseball)

print(type(np_baseball))

print(np_baseball.shape)





<class 'numpy.ndarray'>
(4, 2)


* Carguemos los 1014 registros en un arreglo bidimensional en el que cada renglón contenga el peso y la estatura de los jugadores. (Imprimir)

* Mostremos solo la columna del peso (Imprimir) dentro del arreglo bidimensional

In [67]:
baseball=[]
type(baseball)
for i in range(len(bmi)):
    baseball.append( [height_in[i] , weight_lb[i]])
np_baseball=np.array(baseball)    
print(baseball)
#type(baseball)

[[67, 233], [73, 268], [83, 237], [80, 195], [67, 192], [73, 270], [73, 234], [82, 264], [74, 154], [76, 286], [78, 234], [81, 259], [79, 257], [69, 211], [71, 156], [73, 286], [74, 194], [80, 180], [73, 239], [78, 159], [75, 156], [78, 150], [76, 229], [67, 265], [82, 242], [81, 209], [67, 195], [71, 218], [72, 220], [67, 204], [82, 166], [75, 266], [70, 232], [68, 237], [73, 199], [73, 254], [72, 232], [68, 168], [70, 181], [79, 252], [75, 257], [68, 183], [69, 207], [79, 205], [82, 273], [75, 160], [82, 254], [79, 268], [71, 259], [75, 212], [78, 212], [67, 161], [68, 186], [74, 192], [76, 171], [77, 229], [81, 262], [75, 223], [83, 272], [69, 173], [82, 280], [81, 191], [69, 159], [69, 219], [79, 232], [71, 213], [67, 162], [73, 198], [73, 213], [76, 215], [75, 278], [68, 282], [83, 284], [71, 272], [70, 171], [82, 183], [68, 222], [75, 220], [69, 236], [78, 199], [77, 216], [83, 208], [67, 229], [73, 249], [72, 186], [77, 168], [76, 227], [73, 198], [71, 166], [71, 190], [76, 232]

In [68]:
print(np_baseball[:,1] )

[233 268 237 ... 228 208 168]


### Unir dos arreglos en 1 

En el ejemplo anterior vimos como al arreglo `baseball[]` se le añadieron dos series  por medio del método `append` y recorriendolos en un ciclo.

Numpy cuenta con un método que adjunta las series de manera más sencilla, por medio del método **np.column_stack()**

Así, tendríamos el mismo resultado con unas cuantas lineas de código menos.

~~~py
baseball=np.column_stack((height_in,weight_lb))
~~~

### Media vs Promedio

Podemos calcular la Media y el Promedio de una serie con las funciones Numpy

~~~py
np.mean(serie)
np.median(serie)
np.std(serie)
np.corrcoef(x=serie1,y=serie2)
~~~

